eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
---
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: P@ssw0rd
    
  jpa:
    hibernate:
      ddl-auto: update    

---
# Zipkin configuration after adding dependecy
spring:
  zipkin:
    base-url: http://localhost:9411
    
    
address:
  test:
    env: deva